# Generated by Django 5.0.7 on 2026-08-01 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='users.skill'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-published_at'], name='jobs_job_status_a9561c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['work_mode'], name='jobs_job_work_mo_424767_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_job_experie_09027f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('candidate', 'job')},
        ),
    ]
