# Generated by Django 5.0.7 on 2026-08-01 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('profile_update', 'Profile Update'), ('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('job_deleted', 'Job Deleted'), ('application_submitted', 'Application Submitted'), ('application_status_changed', 'Application Status Changed'), ('resume_uploaded', 'Resume Uploaded'), ('interview_scheduled', 'Interview Scheduled'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
